version: '3'

services:
  dockerserver:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dockercicd
    ports:
      - "5000:5000"
    restart: always
    volumes:
      - .:/app
